version: '3'

services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      # for testing the app directly without SSL; disable this port in production
      - "8501:8501"
    # --server.baseUrlPath specifies the base URL path for the app, that is configured in Nginx project.conf
    command: streamlit run src/streamlit_ui.py --server.baseUrlPath c2g --server.enableCORS=false

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
