version: '3'

services:
  app:
    container_name: app
    restart: always
    build: .
    # For testing the app directly without SSL; disable this port in production
    # ports:
      # - "8501:8501"
    volumes:
      # Mount files with secrets
      - ./.env_local:/app/.env_local:ro
      - ./gdrive_service_account.json:/app/gdrive_service_account.json:ro
    # --server.baseUrlPath specifies the base URL path for the app, that is configured in Nginx project.conf
    command: streamlit run src/streamlit_ui.py --server.baseUrlPath c2g --server.enableCORS=false

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      # Leave port 80 open for use by certbot to renew SSL certificate: sudo certbot renew --dry-run
      # - "80:80"
      - "443:443"
    volumes:
      # Mount SSL certificate files
      # When certificates are renewed (every 90 days using certbot), contents from the new files from
      # /etc/letsencrypt/live/confl2gdrive.navalabs.co/* will need to be copied to these mounted files
      # TODO: create a script to automate this when the instance reboots
      - ./nginx/fullchain.pem:/etc/ssl/certs/certificate.pem:ro
      - ./nginx/privkey.pem:/etc/ssl/private/key.pem:ro
    depends_on:
      - app
